### ISSUE TITLE
No DB connection because occ config:system:get doesn't always return a proper value

### ISSUE THREAD

**Issue by DrMurx** [cloud-py-api/cloud_py_api#46]
**Describe the bug**

If Nextcloud's database config is done via environment variables (possible with variables named `NC_<cfgvalue>`, see [PR 3966](https://github.com/nextcloud/server/pull/3966)), `occ config:system:get` does not respect this and cloud_py_api can't connect to the database.

I opened a [Nextcloud bug](https://github.com/nextcloud/server/pull/3966) on this subject because I think the `occ` command should reliably return the configuration, but one could still argue that `occ config:system:get` should only complement the functionality of `occ config:system:set` and only operate on the `config.php`. Therefore you might want to explore other options on your side.

**To Reproduce**

See instructions in https://github.com/nextcloud/server/issues/36126

**Expected behavior**

Working database connection, regardless of how it is configured.

**Comment by bigcat88** [comment]
Thanks @DrMurx for pointing on this, good catch!

**Comment by DrMurx** [comment]
Given that a config via environment variable is mainly used in container environments, there is another option to solve this. Doing things the "docker way" means to run dedicated containers for specific services. 

So instead of spawning the MediaDC instance (or any other cloud_py_api based service) from `mod_php` or `php-fpm`, it could run in a dedicated container. 

There's a similar discussion around Nextcloud's very own `notify_push` in https://github.com/nextcloud/docker/issues/1422 with a simple container solution described in [this comment](https://github.com/nextcloud/docker/issues/1422#issuecomment-783671955). 

Note that `notify_push` parses the `config.php` directly with a complicated PHP parsing logic in Go (🤦 ), so it neither accepts the `NC_` variables nor does it respect [additional config files](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#multiple-config-php-file). But it understands dedicated variables like `DATABASE_URL`, `DATABASE_PREFIX` and `REDIS_URL`.

**Comment by bigcat88** [comment]
@DrMurx if I understand right, that is what is needed

**Comment by DrMurx** [comment]
Yes, PR #47 should resolve the current issue.

I'd still suggest to make projects that base on cloud_py_api docker-friendly. Should I open a new issue for such a feature?

**Comment by bigcat88** [comment]
Yes, it's better to do it in the new issue.
